// Normalized data structure for all areas and suburbs
// This file contains all area and suburb related data in one place

import type { Area, Suburb, AreasData, SuburbsData } from "./types";

export const areas: AreasData = {
  byId: {
    sydney: {
      id: "sydney",
      name: "Sydney",
      state: "NSW",
      displayName: "Sydney's Trusted Mortgage Experts",
      tagline: "Our Home Base",
      description:
        "Based in the heart of Sydney, we've been helping locals secure their dream homes and investment properties across all Sydney suburbs for over 15 years.",
      heroImage:
        "https://images.unsplash.com/photo-1717883560409-14adc1074f0e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx8fDE3NTU4NjE2ODd8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
      gradient: "from-blue-900 via-purple-900 to-pink-800",
      accentColor: "blue",
      phone: "Call Our Sydney Office",
      stats: {
        clients: "500+",
        loans: "$250M+",
        suburbs: "25+",
        rating: "4.9/5",
      },
      statsLabels: {
        clients: "Sydney Clients Served",
        loans: "In Sydney Home Loans",
        suburbs: "Sydney Suburbs Covered",
        rating: "Sydney Client Rating",
      },
      services: [
        {
          title: "First Home Buyer Assistance",
          description:
            "Navigate Sydney's competitive market with expert guidance",
        },
        {
          title: "Investment Property Loans",
          description: "Capitalize on Sydney's strong rental market",
        },
        {
          title: "Commercial Property Finance",
          description: "Secure prime Sydney commercial real estate",
        },
        {
          title: "Refinancing Solutions",
          description:
            "Switch to better rates and save on your Sydney property",
        },
      ],
      suburbs: [
        "sydney-cbd",
        "parramatta",
        "bondi",
        "manly",
        "chatswood",
        "penrith",
      ],
      otherSuburbs: [
        "Hornsby",
        "Liverpool",
        "Bankstown",
        "Blacktown",
        "Campbelltown",
        "Sutherland",
      ],
      route: "/areas/sydney",
    },
    melbourne: {
      id: "melbourne",
      name: "Melbourne",
      state: "VIC",
      displayName: "Melbourne Mortgage & Finance Experts",
      tagline: "Melbourne, Victoria",
      description:
        "Your trusted mortgage brokers serving Melbourne and surrounding suburbs. We understand Victoria's property market and help you secure the best home loan deals across Melbourne's diverse neighborhoods.",
      heroImage:
        "https://images.unsplash.com/photo-1545044846-351ba102b6d5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
      gradient: "from-purple-900 via-indigo-900 to-purple-800",
      accentColor: "purple",
      phone: "(03) 9000 0000",
      stats: {
        clients: "400+",
        loans: "$200M+",
        suburbs: "30+",
        rating: "4.9/5",
      },
      statsLabels: {
        clients: "Melbourne Clients Served",
        loans: "In Melbourne Home Loans",
        suburbs: "Melbourne Suburbs Covered",
        rating: "Melbourne Client Rating",
      },
      services: [
        {
          title: "First Home Buyer Melbourne",
          description: "Special programs for Melbourne first-time buyers",
        },
        {
          title: "Melbourne Investment Loans",
          description: "Capitalize on Melbourne's rental market opportunities",
        },
        {
          title: "Melbourne Refinancing",
          description: "Switch to better rates for your Melbourne property",
        },
      ],
      suburbs: [
        "melbourne-cbd",
        "south-yarra",
        "brighton",
        "richmond",
        "st-kilda",
        "docklands",
      ],
      otherSuburbs: [
        "Fitzroy",
        "Carlton",
        "Prahran",
        "Toorak",
        "Hawthorn",
        "Camberwell",
      ],
      route: "/areas/melbourne",
    },
    perth: {
      id: "perth",
      name: "Perth",
      state: "WA",
      displayName: "Perth Mortgage & Finance Specialists",
      tagline: "Perth, Western Australia",
      description:
        "Expert mortgage brokers serving Perth and WA suburbs. We understand the unique Western Australian property market and help you secure competitive home loan rates across Perth's growing regions.",
      heroImage:
        "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
      gradient: "from-orange-900 via-red-900 to-pink-800",
      accentColor: "orange",
      phone: "(08) 9000 0000",
      stats: {
        clients: "300+",
        loans: "$180M+",
        suburbs: "20+",
        rating: "4.8/5",
      },
      statsLabels: {
        clients: "Perth Clients Served",
        loans: "In Perth Home Loans",
        suburbs: "Perth Suburbs Covered",
        rating: "Perth Client Rating",
      },
      services: [
        {
          title: "Perth First Home Buyers",
          description: "Navigate WA's first home buyer incentives and grants",
        },
        {
          title: "Perth Investment Properties",
          description: "Capitalize on Perth's mining boom and rental growth",
        },
        {
          title: "Perth Refinancing",
          description: "Switch to better rates for your Perth property",
        },
      ],
      suburbs: [
        "perth-cbd",
        "fremantle",
        "joondalup",
        "subiaco",
        "mandurah",
        "rockingham",
      ],
      otherSuburbs: [
        "Scarborough",
        "Cottesloe",
        "Midland",
        "Armadale",
        "Kalamunda",
        "Wanneroo",
      ],
      route: "/areas/perth",
    },
    adelaide: {
      id: "adelaide",
      name: "Adelaide",
      state: "SA",
      displayName: "Adelaide Mortgage & Finance Experts",
      tagline: "Adelaide, South Australia",
      description:
        "Professional mortgage brokers serving Adelaide and surrounding SA regions. We help you navigate South Australia's property market with expert local knowledge and competitive home loan solutions.",
      heroImage:
        "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
      gradient: "from-green-900 via-teal-900 to-blue-800",
      accentColor: "green",
      phone: "(08) 8000 0000",
      stats: {
        clients: "250+",
        loans: "$120M+",
        suburbs: "18+",
        rating: "4.8/5",
      },
      statsLabels: {
        clients: "Adelaide Clients Served",
        loans: "In Adelaide Home Loans",
        suburbs: "Adelaide Suburbs Covered",
        rating: "Adelaide Client Rating",
      },
      services: [
        {
          title: "Adelaide First Home Buyers",
          description: "Take advantage of SA's affordable property market",
        },
        {
          title: "Adelaide Investment Loans",
          description: "Invest in Adelaide's steady growth market",
        },
        {
          title: "Adelaide Refinancing",
          description: "Secure better rates for your Adelaide property",
        },
      ],
      suburbs: ["adelaide-cbd", "glenelg"],
      otherSuburbs: [
        "North Adelaide",
        "Burnside",
        "Unley",
        "Norwood",
        "Prospect",
        "Mitcham",
      ],
      route: "/areas/adelaide",
    },
    penrith: {
      id: "penrith",
      name: "Penrith",
      state: "NSW",
      displayName: "Penrith Area Mortgage Specialists",
      tagline: "Greater Western Sydney",
      description:
        "Expert mortgage services for Penrith and the greater western Sydney region. We understand the local market dynamics and help families and investors secure the best home loan deals in this growing corridor.",
      heroImage:
        "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
      gradient: "from-indigo-900 via-blue-900 to-teal-800",
      accentColor: "indigo",
      phone: "(02) 4700 0000",
      stats: {
        clients: "200+",
        loans: "$100M+",
        suburbs: "15+",
        rating: "4.8/5",
      },
      statsLabels: {
        clients: "Penrith Clients Served",
        loans: "In Penrith Home Loans",
        suburbs: "Penrith Areas Covered",
        rating: "Penrith Client Rating",
      },
      services: [
        {
          title: "Penrith First Home Buyers",
          description: "Affordable entry into the Sydney property market",
        },
        {
          title: "Penrith Investment Properties",
          description: "Capitalize on western Sydney's growth corridor",
        },
        {
          title: "Penrith Refinancing",
          description: "Better rates for your western Sydney property",
        },
      ],
      suburbs: [],
      otherSuburbs: [
        "Penrith CBD",
        "Kingswood",
        "St Marys",
        "Mount Druitt",
        "Blacktown",
        "Richmond",
      ],
      route: "/areas/penrith",
    },
    parramatta: {
      id: "parramatta",
      name: "Parramatta",
      state: "NSW",
      displayName: "Parramatta Business District Mortgage Experts",
      tagline: "Sydney's Second CBD",
      description:
        "Specialized mortgage services for Parramatta and surrounding business districts. As Sydney's second CBD rapidly develops, we help you secure optimal financing for both residential and commercial properties in this thriving hub.",
      heroImage:
        "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
      gradient: "from-cyan-900 via-blue-900 to-indigo-800",
      accentColor: "cyan",
      phone: "(02) 9600 0000",
      stats: {
        clients: "180+",
        loans: "$90M+",
        suburbs: "12+",
        rating: "4.9/5",
      },
      statsLabels: {
        clients: "Parramatta Clients Served",
        loans: "In Parramatta Home Loans",
        suburbs: "Parramatta Areas Covered",
        rating: "Parramatta Client Rating",
      },
      services: [
        {
          title: "Parramatta CBD Properties",
          description: "Secure prime real estate in Sydney's second CBD",
        },
        {
          title: "Parramatta Investment Loans",
          description: "Capitalize on the rapid urban development",
        },
        {
          title: "Commercial Finance Parramatta",
          description: "Business loans for the growing commercial district",
        },
      ],
      suburbs: [],
      otherSuburbs: [
        "Harris Park",
        "Westmead",
        "Granville",
        "Auburn",
        "Merrylands",
        "Fairfield",
      ],
      route: "/areas/parramatta",
    },
  },
  allIds: ["sydney", "melbourne", "perth", "adelaide", "penrith", "parramatta"],
};

export const suburbs: SuburbsData = {
  byId: {
    "sydney-cbd": {
      id: "sydney-cbd",
      areaId: "sydney",
      name: "Sydney CBD",
      slug: "cbd",
      description:
        "Experience city living at its finest in Sydney's bustling Central Business District. From luxury apartments to heritage properties, the CBD offers unparalleled lifestyle and investment opportunities.",
      medianPrice: "$1.8M",
      growth: "+5.2%",
      population: "17,252",
      features: [
        "World-class dining and entertainment",
        "Prime public transport connectivity",
        "Walking distance to major attractions",
        "High rental yields for investors",
        "24/7 vibrant city lifestyle",
        "Premium office spaces and business hubs",
      ],
      nearbySuburbs: ["The Rocks", "Darling Harbour", "Pyrmont", "Surry Hills"],
      imageQuery: "sydney city buildings",
      route: "/areas/sydney/suburbs/cbd",
    },
    parramatta: {
      id: "parramatta",
      areaId: "sydney",
      name: "Parramatta",
      slug: "parramatta",
      description:
        "Sydney's second CBD offers excellent value and growth potential. Modern apartments, business opportunities, and great transport links make Parramatta ideal for both living and investing.",
      medianPrice: "$850K",
      growth: "+7.1%",
      population: "25,000",
      features: [
        "Sydney's second CBD",
        "Major transport interchange",
        "Growing business district",
        "Affordable compared to CBD",
        "Strong rental demand",
        "Major redevelopment projects",
      ],
      nearbySuburbs: ["Harris Park", "Westmead", "Granville", "Auburn"],
      imageQuery: "parramatta sydney skyline",
      route: "/areas/sydney/suburbs/parramatta",
    },
    bondi: {
      id: "bondi",
      areaId: "sydney",
      name: "Bondi",
      slug: "bondi",
      description:
        "Live the ultimate beach lifestyle in one of Sydney's most iconic coastal suburbs. Bondi offers premium beachside living with strong investment potential and global recognition.",
      medianPrice: "$2.1M",
      growth: "+3.8%",
      population: "11,647",
      features: [
        "World-famous Bondi Beach",
        "Vibrant cafe and restaurant scene",
        "Coastal walk to Coogee",
        "Strong tourism and rental market",
        "Boutique shopping strips",
        "Premium beachside lifestyle",
      ],
      nearbySuburbs: ["Bondi Junction", "Bronte", "Tamarama", "Waverley"],
      imageQuery: "bondi beach sydney",
      route: "/areas/sydney/suburbs/bondi",
    },
    manly: {
      id: "manly",
      areaId: "sydney",
      name: "Manly",
      slug: "manly",
      description:
        "Enjoy the perfect balance of beach lifestyle and city accessibility. Manly offers stunning beaches, ferry connections to the CBD, and a relaxed coastal community atmosphere.",
      medianPrice: "$1.9M",
      growth: "+4.2%",
      population: "16,500",
      features: [
        "Beautiful beaches and surfing",
        "Ferry connection to CBD",
        "The Corso pedestrian mall",
        "Manly Sea Life Sanctuary nearby",
        "Strong tourist and rental market",
        "Relaxed beachside community",
      ],
      nearbySuburbs: ["Fairlight", "Balgowlah", "Seaforth", "Queenscliff"],
      imageQuery: "manly beach sydney",
      route: "/areas/sydney/suburbs/manly",
    },
    chatswood: {
      id: "chatswood",
      areaId: "sydney",
      name: "Chatswood",
      slug: "chatswood",
      description:
        "Experience the convenience of Chatswood's major shopping and transport hub. With excellent schools, diverse dining, and strong Asian community, it's perfect for families and professionals.",
      medianPrice: "$1.4M",
      growth: "+5.8%",
      population: "22,000",
      features: [
        "Major shopping and retail hub",
        "Excellent transport connections",
        "Top-rated schools nearby",
        "Diverse multicultural community",
        "Growing high-rise developments",
        "Strong rental and resale market",
      ],
      nearbySuburbs: ["Willoughby", "Artarmon", "Lane Cove", "Roseville"],
      imageQuery: "chatswood sydney shopping",
      route: "/areas/sydney/suburbs/chatswood",
    },
    penrith: {
      id: "penrith",
      areaId: "sydney",
      name: "Penrith",
      slug: "penrith",
      description:
        "Discover affordable family living in Sydney's growing western corridor. Penrith offers great value, new developments, and excellent transport links to the CBD and Blue Mountains.",
      medianPrice: "$680K",
      growth: "+8.5%",
      population: "15,000",
      features: [
        "Affordable entry into Sydney market",
        "Growing transport infrastructure",
        "Close to Blue Mountains",
        "Family-friendly community",
        "New residential developments",
        "Strong growth potential",
      ],
      nearbySuburbs: ["Kingswood", "St Marys", "Blacktown", "Mount Druitt"],
      imageQuery: "penrith sydney suburban",
      route: "/areas/sydney/suburbs/penrith",
    },
    "melbourne-cbd": {
      id: "melbourne-cbd",
      areaId: "melbourne",
      name: "Melbourne CBD",
      slug: "cbd",
      description:
        "Experience the heart of Melbourne's business and cultural district. The CBD offers modern apartments, world-class dining, and unmatched convenience with excellent investment potential.",
      medianPrice: "$720K",
      growth: "+2.8%",
      population: "37,000",
      features: [
        "Heart of Melbourne's business district",
        "World-class dining and entertainment",
        "Excellent public transport connections",
        "Cultural attractions and events",
        "High rental yields",
        "Growing residential population",
      ],
      nearbySuburbs: ["Southbank", "Docklands", "Carlton", "East Melbourne"],
      imageQuery: "melbourne cbd skyline",
      route: "/areas/melbourne/suburbs/cbd",
    },
    "south-yarra": {
      id: "south-yarra",
      areaId: "melbourne",
      name: "South Yarra",
      slug: "south-yarra",
      description:
        "Live in Melbourne's most prestigious and fashionable suburb. South Yarra combines luxury shopping, fine dining, and elegant heritage architecture with excellent tram connections.",
      medianPrice: "$950K",
      growth: "+3.2%",
      population: "22,000",
      features: [
        "Melbourne's most prestigious suburb",
        "Chapel Street shopping and dining",
        "Heritage architecture and character",
        "Excellent tram connections",
        "Royal Botanic Gardens nearby",
        "High-end rental market",
      ],
      nearbySuburbs: ["Toorak", "Prahran", "Richmond", "Windsor"],
      imageQuery: "south yarra melbourne chapel street",
      route: "/areas/melbourne/suburbs/south-yarra",
    },
    brighton: {
      id: "brighton",
      areaId: "melbourne",
      name: "Brighton",
      slug: "brighton",
      description:
        "Enjoy Melbourne's premier beachside lifestyle in Brighton. This prestigious suburb offers beautiful beaches, heritage homes, and excellent schools, making it perfect for families and investors.",
      medianPrice: "$1.3M",
      growth: "+2.5%",
      population: "23,000",
      features: [
        "Premier beachside location",
        "Iconic Brighton Beach boxes",
        "Excellent private schools",
        "Heritage homes and character",
        "Bay Street shopping strip",
        "Strong family market",
      ],
      nearbySuburbs: ["Hampton", "Sandringham", "Bentleigh", "Brighton East"],
      imageQuery: "brighton melbourne beach boxes",
      route: "/areas/melbourne/suburbs/brighton",
    },
    richmond: {
      id: "richmond",
      areaId: "melbourne",
      name: "Richmond",
      slug: "richmond",
      description:
        "Experience Richmond's vibrant inner-city lifestyle. Known for its eclectic mix of old and new, Richmond offers trendy bars, restaurants, and converted warehouses with easy CBD access.",
      medianPrice: "$840K",
      growth: "+4.1%",
      population: "26,000",
      features: [
        "Trendy inner-city lifestyle",
        "Vibrant bar and restaurant scene",
        "Converted warehouse apartments",
        "Bridge Road shopping strip",
        "Close to MCG and sports precinct",
        "Strong rental demand",
      ],
      nearbySuburbs: ["Collingwood", "Fitzroy", "Cremorne", "South Yarra"],
      imageQuery: "richmond melbourne inner city",
      route: "/areas/melbourne/suburbs/richmond",
    },
    "st-kilda": {
      id: "st-kilda",
      areaId: "melbourne",
      name: "St Kilda",
      slug: "st-kilda",
      description:
        "Live Melbourne's bohemian beachside culture in St Kilda. Famous for its pier, foreshore, and vibrant nightlife, St Kilda offers unique character and strong investment opportunities.",
      medianPrice: "$730K",
      growth: "+3.7%",
      population: "19,000",
      features: [
        "Iconic St Kilda Pier and beach",
        "Vibrant arts and music scene",
        "Acland Street cake shops",
        "Luna Park entertainment",
        "Bohemian beachside culture",
        "Strong tourism rental market",
      ],
      nearbySuburbs: ["St Kilda East", "Elwood", "Balaclava", "Windsor"],
      imageQuery: "st kilda melbourne pier",
      route: "/areas/melbourne/suburbs/st-kilda",
    },
    docklands: {
      id: "docklands",
      areaId: "melbourne",
      name: "Docklands",
      slug: "docklands",
      description:
        "Experience modern waterfront living in Melbourne's newest urban precinct. Docklands offers contemporary apartments, shopping, and entertainment with spectacular harbor views and city convenience.",
      medianPrice: "$650K",
      growth: "+1.9%",
      population: "15,000",
      features: [
        "Modern waterfront precinct",
        "Contemporary apartment living",
        "Harbor Town shopping outlet",
        "Waterfront dining and entertainment",
        "Close to CBD and transport",
        "Growing residential community",
      ],
      nearbySuburbs: [
        "Melbourne CBD",
        "West Melbourne",
        "Port Melbourne",
        "Southbank",
      ],
      imageQuery: "docklands melbourne waterfront",
      route: "/areas/melbourne/suburbs/docklands",
    },
    "perth-cbd": {
      id: "perth-cbd",
      areaId: "perth",
      name: "Perth CBD",
      slug: "cbd",
      description:
        "Live in the heart of Western Australia's business capital. Perth CBD offers modern apartments, riverside parks, and vibrant city life with easy access to beaches and business districts.",
      medianPrice: "$550K",
      growth: "+3.5%",
      population: "21,000",
      features: [
        "Heart of WA business district",
        "Swan River and Kings Park nearby",
        "Growing apartment market",
        "Excellent transport connections",
        "Vibrant nightlife and dining",
        "Strong rental yields",
      ],
      nearbySuburbs: ["Northbridge", "West Perth", "East Perth", "South Perth"],
      imageQuery: "perth cbd skyline swan river",
      route: "/areas/perth/suburbs/cbd",
    },
    fremantle: {
      id: "fremantle",
      areaId: "perth",
      name: "Fremantle",
      slug: "fremantle",
      description:
        "Discover the historic charm and vibrant culture of Fremantle. This port city offers heritage architecture, bustling markets, and coastal lifestyle with excellent growth prospects.",
      medianPrice: "$720K",
      growth: "+5.1%",
      population: "29,000",
      features: [
        "Historic port city charm",
        "Fremantle Markets and cafe culture",
        "Beautiful heritage architecture",
        "Close to beaches and harbor",
        "Strong tourism and rental market",
        "Arts and cultural hub",
      ],
      nearbySuburbs: [
        "South Fremantle",
        "White Gum Valley",
        "Beaconsfield",
        "Hamilton Hill",
      ],
      imageQuery: "fremantle perth historic",
      route: "/areas/perth/suburbs/fremantle",
    },
    joondalup: {
      id: "joondalup",
      areaId: "perth",
      name: "Joondalup",
      slug: "joondalup",
      description:
        "Experience the convenience of Perth's northern business hub. Joondalup offers modern amenities, excellent transport, and proximity to beautiful northern beaches with strong growth potential.",
      medianPrice: "$520K",
      growth: "+4.8%",
      population: "33,000",
      features: [
        "Major northern business hub",
        "Modern shopping and facilities",
        "Train line to Perth CBD",
        "Close to northern beaches",
        "ECU Joondalup campus nearby",
        "Growing family community",
      ],
      nearbySuburbs: ["Currambine", "Iluka", "Burns Beach", "Kinross"],
      imageQuery: "joondalup perth business district",
      route: "/areas/perth/suburbs/joondalup",
    },
    subiaco: {
      id: "subiaco",
      areaId: "perth",
      name: "Subiaco",
      slug: "subiaco",
      description:
        "Live in Perth's trendy inner-western suburb known for its vibrant cafe culture, boutique shopping, and proximity to the city. Subiaco offers character homes and modern apartments with excellent amenities.",
      medianPrice: "$680K",
      growth: "+3.9%",
      population: "19,000",
      features: [
        "Trendy inner-western suburb",
        "Vibrant Rokeby Road dining",
        "Subiaco Oval entertainment",
        "Character homes and modern apartments",
        "Close to Perth CBD",
        "Strong rental market",
      ],
      nearbySuburbs: ["West Perth", "Shenton Park", "Daglish", "Nedlands"],
      imageQuery: "subiaco perth rokeby road",
      route: "/areas/perth/suburbs/subiaco",
    },
    mandurah: {
      id: "mandurah",
      areaId: "perth",
      name: "Mandurah",
      slug: "mandurah",
      description:
        "Enjoy relaxed coastal living in Western Australia's premier waterfront city. Mandurah offers beautiful waterways, recreational boating, and affordable family lifestyle with growing popularity.",
      medianPrice: "$480K",
      growth: "+6.2%",
      population: "84,000",
      features: [
        "Premier waterfront city",
        "Beautiful waterways and canals",
        "Recreational boating lifestyle",
        "Affordable family living",
        "Growing retirement community",
        "Strong tourism market",
      ],
      nearbySuburbs: ["Halls Head", "Dawesville", "Greenfields", "Falcon"],
      imageQuery: "mandurah perth waterfront canals",
      route: "/areas/perth/suburbs/mandurah",
    },
    rockingham: {
      id: "rockingham",
      areaId: "perth",
      name: "Rockingham",
      slug: "rockingham",
      description:
        "Discover affordable coastal living south of Perth. Rockingham offers beautiful beaches, growing infrastructure, and excellent value for families and first home buyers in Perth's expanding corridor.",
      medianPrice: "$450K",
      growth: "+7.3%",
      population: "109,000",
      features: [
        "Affordable coastal living",
        "Beautiful beaches and bays",
        "Growing infrastructure investment",
        "Family-friendly community",
        "Excellent value for money",
        "Strong growth corridor",
      ],
      nearbySuburbs: [
        "Safety Bay",
        "Warnbro",
        "Port Kennedy",
        "Secret Harbour",
      ],
      imageQuery: "rockingham perth beach coastal",
      route: "/areas/perth/suburbs/rockingham",
    },
    "adelaide-cbd": {
      id: "adelaide-cbd",
      areaId: "adelaide",
      name: "Adelaide CBD",
      slug: "cbd",
      description:
        "Experience the heart of South Australia's capital city. Adelaide CBD offers elegant heritage architecture, world-class dining, and convenient city living with excellent value compared to other capitals.",
      medianPrice: "$420K",
      growth: "+2.1%",
      population: "25,000",
      features: [
        "Elegant heritage architecture",
        "World-class dining scene",
        "Free city circle tram",
        "Central Market nearby",
        "Adelaide Festival Centre",
        "Excellent value for capital city",
      ],
      nearbySuburbs: ["North Adelaide", "Parklands", "Kent Town", "Thebarton"],
      imageQuery: "adelaide cbd heritage architecture",
      route: "/areas/adelaide/suburbs/cbd",
    },
    glenelg: {
      id: "glenelg",
      areaId: "adelaide",
      name: "Glenelg",
      slug: "glenelg",
      description:
        "Enjoy Adelaide's premier beachside lifestyle in historic Glenelg. Famous for its jetty, beach, and tram connection to the city, Glenelg offers relaxed coastal living with strong rental appeal.",
      medianPrice: "$620K",
      growth: "+3.4%",
      population: "15,500",
      features: [
        "Historic beachside suburb",
        "Famous Glenelg Jetty and beach",
        "Direct tram to Adelaide CBD",
        "Jetty Road shopping strip",
        "Strong tourism and rental market",
        "Relaxed coastal lifestyle",
      ],
      nearbySuburbs: [
        "Glenelg North",
        "Glenelg South",
        "Brighton",
        "Somerton Park",
      ],
      imageQuery: "glenelg adelaide beach jetty",
      route: "/areas/adelaide/suburbs/glenelg",
    },
  },
  allIds: [
    "sydney-cbd",
    "parramatta",
    "bondi",
    "manly",
    "chatswood",
    "penrith",
    "melbourne-cbd",
    "south-yarra",
    "brighton",
    "richmond",
    "st-kilda",
    "docklands",
    "perth-cbd",
    "fremantle",
    "joondalup",
    "subiaco",
    "mandurah",
    "rockingham",
    "adelaide-cbd",
    "glenelg",
  ],
};

// Helper functions to work with the normalized data
export const getAreaById = (areaId: string): Area | undefined =>
  areas.byId[areaId];
export const getSuburbById = (suburbId: string): Suburb | undefined =>
  suburbs.byId[suburbId];
export const getSuburbsByAreaId = (areaId: string): Suburb[] => {
  return (
    areas.byId[areaId]?.suburbs?.map((suburbId) => suburbs.byId[suburbId]) || []
  );
};
export const getAllAreas = (): Area[] =>
  areas.allIds.map((id) => areas.byId[id]);
export const getAllSuburbs = (): Suburb[] =>
  suburbs.allIds.map((id) => suburbs.byId[id]);

// Route helpers
export const getAreaRoute = (areaId: string): string | undefined =>
  areas.byId[areaId]?.route;
export const getSuburbRoute = (suburbId: string): string | undefined =>
  suburbs.byId[suburbId]?.route;
