// Normalized data structure for all areas and suburbs
// This file contains all area and suburb related data in one place

import type {
  Area,
  Suburb,
  AreasData,
  SuburbsData,
  SuburbService,
  SuburbPageTexts,
  NavigationItem,
  NavigationSection,
} from "./types";

// Company Information
export const COMPANY_INFO = {
  name: "My Choice",
  fullName: "My Choice Mortgage & Finance",
  tagline: "Mortgage & Finance",
  description:
    "Expert mortgage brokers providing home loans, personal finance, and commercial finance solutions across Australia.",
  phone: "0402 742 493",
  email: "info@mychoicemortgagefinance.com.au",
  address: "NSW 2749, AUSTRALIA",
  website: "https://www.mychoicemortgagefinance.com.au",
  logo: "/logo.png",
  established: "2009",
  creditRepNumber: "123456",
} as const;

// Main Services
export const SERVICES = {
  main: [
    {
      id: "first-home-buyers",
      title: "First Home Buyers",
      description: "Expert guidance for first-time property buyers",
      href: "/services/first-home-buyers",
      icon: "Home",
    },
    {
      id: "low-doc-loans",
      title: "Low Doc Loans",
      description: "Flexible documentation loans for self-employed",
      href: "/services/low-doc-loans",
      icon: "FileText",
    },
    {
      id: "smsf",
      title: "SMSF",
      description: "Self-managed super fund property investment loans",
      href: "/services/smsf",
      icon: "PiggyBank",
    },
    {
      id: "construction-loans",
      title: "Construction Loans",
      description: "Progressive funding for new home construction",
      href: "/services/construction-loans",
      icon: "Building",
    },
    {
      id: "debt-consolidation",
      title: "Debt Consolidation",
      description: "Simplify your finances with consolidated loans",
      href: "/services/debt-consolidation",
      icon: "CreditCard",
    },
    {
      id: "refinancing",
      title: "Refinancing",
      description: "Switch to better rates and save on your mortgage",
      href: "/services/refinancing",
      icon: "RefreshCw",
    },
    {
      id: "property-investment",
      title: "Property Investment",
      description: "Investment property loans and portfolio building",
      href: "/services/property-investment",
      icon: "TrendingUp",
    },
  ],
} as const;

// Helper function to generate common suburb services
function createSuburbServices(suburbName: string): SuburbService[] {
  return [
    {
      title: "First Home Buyer Loans",
      description: `Special rates for first-time buyers in ${suburbName}`,
    },
    {
      title: "Investment Property Loans",
      description: `Capitalize on ${suburbName}'s rental market potential`,
    },
    {
      title: "Refinancing",
      description: `Switch to better rates for your ${suburbName} property`,
    },
    {
      title: "Property Valuation",
      description: `Free property valuations for ${suburbName} homes`,
    },
  ];
}

// Helper function to generate common suburb page texts
function createSuburbPageTexts(): SuburbPageTexts {
  return {
    heroSubtitle: SERVICES.main[0].title, // Dynamically use first service (Home Loans)
    primaryCTAButton: "Get {suburb} Quote",
    secondaryCTAButton: "Call Our Team",
    marketInsightsTitle: "{suburb} Market Insights",
    marketInsightsSubtitle: "Current market data for {suburb}",
    medianPriceLabel: "Median House Price",
    growthLabel: "Annual Growth",
    populationLabel: "Population",
    featuresTitle: "Why Choose {suburb}?",
    featuresSubtitle: "What makes {suburb} a great place to live",
    servicesTitle: "{suburb} Finance Services",
    servicesSubtitle: "Specialized lending solutions for {suburb} residents",
    servicesCTAButton: "Get {suburb} Quote",
    nearbyAreasTitle: "Nearby {area} Areas",
    nearbyAreasSubtitle: "We also serve these surrounding areas",
    finalCTATitle: "Ready to Buy in {suburb}?",
    finalCTADescription:
      "Our {suburb} specialists are here to guide you through every step of the home buying process.",
    finalPrimaryCTA: "Start Your {suburb} Application",
    finalSecondaryCTA: "Contact Our {suburb} Team",
  };
}

export const areas: AreasData = {
  byId: {
    sydney: {
      id: "sydney",
      name: "Sydney",
      state: "NSW",
      displayName: "Sydney's Trusted Mortgage Experts",
      tagline: "Our Home Base",
      description:
        "Based in the heart of Sydney, we've been helping locals secure their dream homes and investment properties across all Sydney suburbs for over 15 years.",
      heroImage:
        "https://images.unsplash.com/photo-1717883560409-14adc1074f0e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx8fDE3NTU4NjE2ODd8MA&ixlib=rb-4.1.0&q=80&w=2070&utm_source=figma&utm_medium=referral",
      gradient: "from-blue-600 to-purple-600",
      phone: "Call Our Sydney Office",
      stats: {
        clients: "500+",
        loans: "$250M+",
        suburbs: "25+",
        rating: "4.9/5",
      },
      statsLabels: {
        clients: "Sydney Clients Served",
        loans: "In Sydney Home Loans",
        suburbs: "Sydney Suburbs Covered",
        rating: "Sydney Client Rating",
      },
      services: [
        {
          title: "First Home Buyer Assistance",
          description:
            "Navigate Sydney's competitive market with expert guidance",
          icon: "Home",
        },
        {
          title: "Investment Property Loans",
          description: "Capitalize on Sydney's strong rental market",
          icon: "Building",
        },
        {
          title: "Commercial Property Finance",
          description: "Secure prime Sydney commercial real estate",
          icon: "Building",
        },
        {
          title: "Refinancing Solutions",
          description:
            "Switch to better rates and save on your Sydney property",
          icon: "Star",
        },
      ],
      suburbs: [
        "sydney-cbd",
        "sydney-bondi",
        "sydney-manly",
        "sydney-chatswood",
        "sydney-hornsby",
        "sydney-liverpool",
        "sydney-bankstown",
        "sydney-blacktown",
      ],
      otherSuburbs: [
        "Hornsby",
        "Liverpool",
        "Bankstown",
        "Blacktown",
        "Campbelltown",
        "Sutherland",
      ],
      route: "/areas/sydney",
      office: {
        address: COMPANY_INFO.address,
        phone: COMPANY_INFO.phone,
        hours: "Mon-Fri: 9AM-6PM | Sat: 9AM-2PM",
      },
      marketInsights: {
        medianPrice: "$1.2M",
        loanRates: "from 5.99%*",
        grants: "Up to $25K",
      },
      pageTexts: {
        statsSubheading: "Our track record speaks for itself",
        servicesSubheading:
          "Local expertise for Sydney's unique property market",
        suburbsDescription:
          "From the CBD to the outer suburbs, we serve clients across Greater Sydney",
        featuredSuburbsTitle: "Featured Sydney Areas",
        otherSuburbsTitle: "Other Sydney Areas We Serve",
        suburbsCallout:
          "Don't see your suburb? We serve all of Greater Sydney!",
        officeTitle: "Visit Our Sydney Office",
        officeDescription:
          "Located in the heart of Sydney's business district, our team of local mortgage specialists is ready to help you navigate Sydney's property market.",
        ctaTitle: "Ready to Buy in Sydney?",
        ctaDescription:
          "Our Sydney-based experts are here to guide you through every step of the home buying process.",
        primaryCTA: "Start Your Sydney Application",
        secondaryCTA: "Call Our Sydney Team",
      },
    },
    melbourne: {
      id: "melbourne",
      name: "Melbourne",
      state: "VIC",
      displayName: "Melbourne Mortgage & Finance Experts",
      tagline: "Melbourne, Victoria",
      description:
        "Your trusted mortgage brokers serving Melbourne and surrounding suburbs. We understand Victoria's property market and help you secure the best home loan deals across Melbourne's diverse neighborhoods.",
      heroImage:
        "https://images.unsplash.com/photo-1545044846-351ba102b6d5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=2070",
      gradient: "from-blue-600 to-purple-600",
      phone: COMPANY_INFO.phone,
      stats: {
        clients: "400+",
        loans: "$200M+",
        suburbs: "30+",
        rating: "4.9/5",
      },
      statsLabels: {
        clients: "Melbourne Clients Served",
        loans: "In Melbourne Home Loans",
        suburbs: "Melbourne Suburbs Covered",
        rating: "Melbourne Client Rating",
      },
      services: [
        {
          title: "First Home Buyer Melbourne",
          description: "Special programs for Melbourne first-time buyers",
          icon: "Home",
        },
        {
          title: "Melbourne Investment Loans",
          description: "Capitalize on Melbourne's rental market opportunities",
          icon: "Building",
        },
        {
          title: "Melbourne Refinancing",
          description: "Switch to better rates for your Melbourne property",
          icon: "Star",
        },
      ],
      suburbs: [
        "melbourne-cbd",
        "melbourne-south-yarra",
        "melbourne-brighton",
        "melbourne-richmond",
        "melbourne-st-kilda",
        "melbourne-docklands",
        "melbourne-fitzroy",
        "melbourne-carlton",
        "melbourne-prahran",
        "melbourne-toorak",
        "melbourne-hawthorn",
        "melbourne-camberwell",
      ],
      otherSuburbs: [
        "Fitzroy",
        "Carlton",
        "Prahran",
        "Toorak",
        "Hawthorn",
        "Camberwell",
      ],
      route: "/areas/melbourne",
    },
    perth: {
      id: "perth",
      name: "Perth",
      state: "WA",
      displayName: "Perth Mortgage & Finance Specialists",
      tagline: "Perth, Western Australia",
      description:
        "Expert mortgage brokers serving Perth and WA suburbs. We understand the unique Western Australian property market and help you secure competitive home loan rates across Perth's growing regions.",
      heroImage:
        "https://images.unsplash.com/photo-1580014942344-ce423d2b885a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=2070",
      gradient: "from-blue-600 to-purple-600",
      phone: COMPANY_INFO.phone,
      stats: {
        clients: "300+",
        loans: "$180M+",
        suburbs: "20+",
        rating: "4.8/5",
      },
      statsLabels: {
        clients: "Perth Clients Served",
        loans: "In Perth Home Loans",
        suburbs: "Perth Suburbs Covered",
        rating: "Perth Client Rating",
      },
      services: [
        {
          title: "Perth First Home Buyers",
          description: "Navigate WA's first home buyer incentives and grants",
          icon: "Home",
        },
        {
          title: "Perth Investment Properties",
          description: "Capitalize on Perth's mining boom and rental growth",
          icon: "Building",
        },
        {
          title: "Perth Refinancing",
          description: "Switch to better rates for your Perth property",
          icon: "Star",
        },
      ],
      suburbs: [
        "perth-cbd",
        "perth-fremantle",
        "perth-joondalup",
        "perth-subiaco",
        "perth-mandurah",
        "perth-rockingham",
        "perth-scarborough",
        "perth-cottesloe",
        "perth-midland",
        "perth-armadale",
        "perth-kalamunda",
        "perth-wanneroo",
      ],
      otherSuburbs: [
        "Scarborough",
        "Cottesloe",
        "Midland",
        "Armadale",
        "Kalamunda",
        "Wanneroo",
      ],
      route: "/areas/perth",
    },
    adelaide: {
      id: "adelaide",
      name: "Adelaide",
      state: "SA",
      displayName: "Adelaide Mortgage & Finance Experts",
      tagline: "Adelaide, South Australia",
      description:
        "Professional mortgage brokers serving Adelaide and surrounding SA regions. We help you navigate South Australia's property market with expert local knowledge and competitive home loan solutions.",
      heroImage:
        "https://images.unsplash.com/photo-1584417259164-370553879731?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=2070",
      gradient: "from-blue-600 to-purple-600",
      phone: COMPANY_INFO.phone,
      stats: {
        clients: "250+",
        loans: "$120M+",
        suburbs: "18+",
        rating: "4.8/5",
      },
      statsLabels: {
        clients: "Adelaide Clients Served",
        loans: "In Adelaide Home Loans",
        suburbs: "Adelaide Suburbs Covered",
        rating: "Adelaide Client Rating",
      },
      services: [
        {
          title: "Adelaide First Home Buyers",
          description: "Take advantage of SA's affordable property market",
          icon: "Home",
        },
        {
          title: "Adelaide Investment Loans",
          description: "Invest in Adelaide's steady growth market",
          icon: "Building",
        },
        {
          title: "Adelaide Refinancing",
          description: "Secure better rates for your Adelaide property",
          icon: "Star",
        },
      ],
      suburbs: ["adelaide-cbd", "adelaide-glenelg"],
      otherSuburbs: [
        "North Adelaide",
        "Burnside",
        "Unley",
        "Norwood",
        "Prospect",
        "Mitcham",
      ],
      route: "/areas/adelaide",
    },
    penrith: {
      id: "penrith",
      name: "Penrith",
      state: "NSW",
      displayName: "Penrith Mortgage & Finance Specialists",
      tagline: "Western Sydney's Growing Hub",
      description:
        "Expert mortgage brokers serving Penrith and the greater Western Sydney region. We understand the dynamic growth in Western Sydney and help you capitalize on excellent property opportunities in this rapidly developing area.",
      heroImage:
        "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=2070",
      gradient: "from-green-600 to-blue-600",
      phone: COMPANY_INFO.phone,
      stats: {
        clients: "350+",
        loans: "$180M+",
        suburbs: "15+",
        rating: "4.8/5",
      },
      statsLabels: {
        clients: "Penrith Clients Served",
        loans: "In Penrith Home Loans",
        suburbs: "Penrith Suburbs Covered",
        rating: "Penrith Client Rating",
      },
      services: [
        {
          title: "First Home Buyer Penrith",
          description: "Take advantage of Western Sydney's affordable market",
          icon: "Home",
        },
        {
          title: "Penrith Investment Loans",
          description: "Capitalize on Penrith's rapid growth and development",
          icon: "Building",
        },
        {
          title: "Penrith Refinancing",
          description: "Switch to better rates for your Penrith property",
          icon: "Star",
        },
      ],
      suburbs: ["penrith-cbd", "penrith-st-marys", "penrith-kingswood"],
      otherSuburbs: [
        "St Clair",
        "Emu Plains",
        "Glenmore Park",
        "Werrington",
        "Cambridge Park",
        "Cranebrook",
      ],
      route: "/areas/penrith",
    },
    parramatta: {
      id: "parramatta",
      name: "Parramatta",
      state: "NSW",
      displayName: "Parramatta Mortgage & Finance Experts",
      tagline: "Sydney's Second CBD",
      description:
        "Professional mortgage brokers serving Parramatta and surrounding Western Sydney areas. As Sydney's second CBD, Parramatta offers exceptional growth potential and we help you secure the best financing for this thriving region.",
      heroImage:
        "https://images.unsplash.com/photo-1590736969955-71cc94901144?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=2070",
      gradient: "from-purple-600 to-pink-600",
      phone: COMPANY_INFO.phone,
      stats: {
        clients: "400+",
        loans: "$220M+",
        suburbs: "20+",
        rating: "4.9/5",
      },
      statsLabels: {
        clients: "Parramatta Clients Served",
        loans: "In Parramatta Home Loans",
        suburbs: "Parramatta Suburbs Covered",
        rating: "Parramatta Client Rating",
      },
      services: [
        {
          title: "Parramatta First Home Buyers",
          description: "Navigate Sydney's second CBD with expert guidance",
          icon: "Home",
        },
        {
          title: "Parramatta Investment Properties",
          description:
            "Invest in Parramatta's booming commercial and residential market",
          icon: "Building",
        },
        {
          title: "Parramatta Commercial Finance",
          description: "Secure prime Parramatta CBD commercial real estate",
          icon: "Building",
        },
        {
          title: "Parramatta Refinancing",
          description: "Switch to better rates for your Parramatta property",
          icon: "Star",
        },
      ],
      suburbs: [
        "parramatta-cbd",
        "parramatta-westmead",
        "parramatta-harris-park",
      ],
      otherSuburbs: [
        "Epping",
        "Carlingford",
        "Telopea",
        "Granville",
        "Auburn",
        "Merrylands",
      ],
      route: "/areas/parramatta",
    },
  },
  allIds: ["sydney", "melbourne", "perth", "adelaide", "penrith", "parramatta"],
};

export const suburbs: SuburbsData = {
  byId: {
    "sydney-cbd": {
      id: "sydney-cbd",
      areaId: "sydney",
      name: "Sydney CBD",
      slug: "cbd",
      description:
        "Experience city living at its finest in Sydney's bustling Central Business District. From luxury apartments to heritage properties, the CBD offers unparalleled lifestyle and investment opportunities.",
      medianPrice: "$1.8M",
      growth: "+5.2%",
      population: "17,252",
      features: [
        "World-class dining and entertainment",
        "Prime public transport connectivity",
        "Walking distance to major attractions",
        "High rental yields for investors",
        "24/7 vibrant city lifestyle",
        "Premium office spaces and business hubs",
      ],
      nearbySuburbs: ["The Rocks", "Darling Harbour", "Pyrmont", "Surry Hills"],
      imageQuery: "sydney city buildings",
      route: "/areas/sydney/suburbs/cbd",
      services: createSuburbServices("Sydney CBD"),
      pageTexts: createSuburbPageTexts(),
    },
    "sydney-bondi": {
      id: "sydney-bondi",
      areaId: "sydney",
      name: "Bondi",
      slug: "bondi",
      description:
        "Live the ultimate beach lifestyle in one of Sydney's most iconic coastal suburbs. Bondi offers premium beachside living with strong investment potential and global recognition.",
      medianPrice: "$2.1M",
      growth: "+3.8%",
      population: "11,647",
      features: [
        "World-famous Bondi Beach",
        "Vibrant cafe and restaurant scene",
        "Coastal walk to Coogee",
        "Strong tourism and rental market",
        "Boutique shopping strips",
        "Premium beachside lifestyle",
      ],
      nearbySuburbs: ["Bondi Junction", "Bronte", "Tamarama", "Waverley"],
      imageQuery: "bondi beach sydney",
      route: "/areas/sydney/suburbs/bondi",
      services: createSuburbServices("Bondi"),
      pageTexts: createSuburbPageTexts(),
    },
    "sydney-manly": {
      id: "sydney-manly",
      areaId: "sydney",
      name: "Manly",
      slug: "manly",
      description:
        "Enjoy the perfect balance of beach lifestyle and city accessibility. Manly offers stunning beaches, ferry connections to the CBD, and a relaxed coastal community atmosphere.",
      medianPrice: "$1.9M",
      growth: "+4.2%",
      population: "16,500",
      features: [
        "Beautiful beaches and surfing",
        "Ferry connection to CBD",
        "The Corso pedestrian mall",
        "Manly Sea Life Sanctuary nearby",
        "Strong tourist and rental market",
        "Relaxed beachside community",
      ],
      nearbySuburbs: ["Fairlight", "Balgowlah", "Seaforth", "Queenscliff"],
      imageQuery: "manly beach sydney",
      route: "/areas/sydney/suburbs/manly",
      services: createSuburbServices("Manly"),
      pageTexts: createSuburbPageTexts(),
    },
    "sydney-chatswood": {
      id: "sydney-chatswood",
      areaId: "sydney",
      name: "Chatswood",
      slug: "chatswood",
      description:
        "Experience the convenience of Chatswood's major shopping and transport hub. With excellent schools, diverse dining, and strong Asian community, it's perfect for families and professionals.",
      medianPrice: "$1.4M",
      growth: "+5.8%",
      population: "22,000",
      features: [
        "Major shopping and retail hub",
        "Excellent transport connections",
        "Top-rated schools nearby",
        "Diverse multicultural community",
        "Growing high-rise developments",
        "Strong rental and resale market",
      ],
      nearbySuburbs: ["Willoughby", "Artarmon", "Lane Cove", "Roseville"],
      imageQuery: "chatswood sydney shopping",
      route: "/areas/sydney/suburbs/chatswood",
      services: createSuburbServices("Chatswood"),
      pageTexts: createSuburbPageTexts(),
    },
    "sydney-hornsby": {
      id: "sydney-hornsby",
      areaId: "sydney",
      name: "Hornsby",
      slug: "hornsby",
      description:
        "Discover family-friendly Hornsby, known for its bushland setting, excellent schools, and convenient transport links. This upper north shore suburb offers great value with strong growth potential.",
      medianPrice: "$1.1M",
      growth: "+6.2%",
      population: "36,000",
      features: [
        "Family-friendly bushland setting",
        "Excellent public and private schools",
        "Major transport interchange",
        "Hornsby Westfield shopping center",
        "Close to national parks",
        "Strong community atmosphere",
      ],
      nearbySuburbs: ["Wahroonga", "Asquith", "Mount Colah", "Berowra"],
      imageQuery: "hornsby sydney bushland families",
      route: "/areas/sydney/suburbs/hornsby",
      services: createSuburbServices("Hornsby"),
      pageTexts: createSuburbPageTexts(),
    },
    "sydney-liverpool": {
      id: "sydney-liverpool",
      areaId: "sydney",
      name: "Liverpool",
      slug: "liverpool",
      description:
        "Experience Liverpool's transformation into a major growth hub. This multicultural city center offers excellent value, major infrastructure projects, and strong investment opportunities in Western Sydney.",
      medianPrice: "$750K",
      growth: "+8.1%",
      population: "43,000",
      features: [
        "Major growth and infrastructure hub",
        "Multicultural community and dining",
        "Liverpool Hospital and health precinct",
        "Growing commercial district",
        "Excellent public transport access",
        "Strong rental yields for investors",
      ],
      nearbySuburbs: ["Casula", "Lurnea", "Warwick Farm", "Cartwright"],
      imageQuery: "liverpool sydney multicultural growth",
      route: "/areas/sydney/suburbs/liverpool",
      services: createSuburbServices("Liverpool"),
      pageTexts: createSuburbPageTexts(),
    },
    "sydney-bankstown": {
      id: "sydney-bankstown",
      areaId: "sydney",
      name: "Bankstown",
      slug: "bankstown",
      description:
        "Discover Bankstown's vibrant multicultural community and excellent value properties. This growing suburb offers diverse dining, good transport links, and strong potential for first home buyers.",
      medianPrice: "$680K",
      growth: "+7.5%",
      population: "34,000",
      features: [
        "Vibrant multicultural community",
        "Excellent value for money",
        "Diverse dining and shopping",
        "Good public transport connections",
        "Growing arts and culture scene",
        "Strong first home buyer market",
      ],
      nearbySuburbs: ["Yagoona", "Condell Park", "Bass Hill", "Revesby"],
      imageQuery: "bankstown sydney multicultural affordable",
      route: "/areas/sydney/suburbs/bankstown",
      services: createSuburbServices("Bankstown"),
      pageTexts: createSuburbPageTexts(),
    },
    "sydney-blacktown": {
      id: "sydney-blacktown",
      areaId: "sydney",
      name: "Blacktown",
      slug: "blacktown",
      description:
        "Explore Blacktown's blend of affordability and growth potential. This major Western Sydney hub offers excellent transport, diverse communities, and great opportunities for families and investors.",
      medianPrice: "$720K",
      growth: "+6.8%",
      population: "47,000",
      features: [
        "Major Western Sydney transport hub",
        "Affordable family properties",
        "Westpoint shopping center",
        "Diverse multicultural community",
        "Growing employment opportunities",
        "Excellent value for investors",
      ],
      nearbySuburbs: ["Seven Hills", "Lalor Park", "Marayong", "Doonside"],
      imageQuery: "blacktown sydney affordable families transport",
      route: "/areas/sydney/suburbs/blacktown",
      services: createSuburbServices("Blacktown"),
      pageTexts: createSuburbPageTexts(),
    },
    "penrith-cbd": {
      id: "penrith-cbd",
      areaId: "penrith",
      name: "Penrith CBD",
      slug: "cbd",
      description:
        "Experience the heart of Western Sydney's growth in Penrith CBD. This thriving business district offers excellent value, major infrastructure developments, and strong investment potential in the growing west.",
      medianPrice: "$620K",
      growth: "+9.2%",
      population: "15,000",
      features: [
        "Major Western Sydney business hub",
        "Penrith Panthers entertainment precinct",
        "Growing commercial and retail district",
        "Excellent train connections to Sydney",
        "Close to Nepean River recreation",
        "Strong growth and development pipeline",
      ],
      nearbySuburbs: ["Kingswood", "St Marys", "Emu Plains", "Cambridge Park"],
      imageQuery: "penrith cbd western sydney business",
      route: "/areas/penrith/suburbs/cbd",
      services: createSuburbServices("Penrith CBD"),
      pageTexts: createSuburbPageTexts(),
    },
    "penrith-st-marys": {
      id: "penrith-st-marys",
      areaId: "penrith",
      name: "St Marys",
      slug: "st-marys",
      description:
        "Discover St Marys' excellent value and family-friendly atmosphere. This growing suburb offers affordable properties, good schools, and convenient access to both Penrith and Sydney CBD.",
      medianPrice: "$580K",
      growth: "+8.7%",
      population: "12,500",
      features: [
        "Excellent value for families",
        "St Marys town center shopping",
        "Good public and private schools",
        "Train station to Sydney CBD",
        "Growing residential developments",
        "Strong rental yields for investors",
      ],
      nearbySuburbs: ["Oxley Park", "Colyton", "Mount Druitt", "Bidwill"],
      imageQuery: "st marys penrith affordable families",
      route: "/areas/penrith/suburbs/st-marys",
      services: createSuburbServices("St Marys"),
      pageTexts: createSuburbPageTexts(),
    },
    "penrith-kingswood": {
      id: "penrith-kingswood",
      areaId: "penrith",
      name: "Kingswood",
      slug: "kingswood",
      description:
        "Experience Kingswood's combination of affordability and convenience. Home to Western Sydney University, this suburb offers great opportunities for families, students, and investors in the growing Penrith region.",
      medianPrice: "$590K",
      growth: "+8.3%",
      population: "8,500",
      features: [
        "Home to Western Sydney University",
        "Affordable properties for families",
        "Close to Penrith CBD and amenities",
        "Good public transport access",
        "Growing student accommodation market",
        "Strong rental demand from university",
      ],
      nearbySuburbs: [
        "Werrington",
        "Cambridge Park",
        "Penrith",
        "South Penrith",
      ],
      imageQuery: "kingswood penrith university affordable",
      route: "/areas/penrith/suburbs/kingswood",
      services: createSuburbServices("Kingswood"),
      pageTexts: createSuburbPageTexts(),
    },
    "parramatta-cbd": {
      id: "parramatta-cbd",
      areaId: "parramatta",
      name: "Parramatta CBD",
      slug: "cbd",
      description:
        "Live in Sydney's second CBD with Parramatta's dynamic business district. This major commercial hub offers modern apartments, excellent transport, and outstanding growth potential in Western Sydney.",
      medianPrice: "$750K",
      growth: "+7.8%",
      population: "23,000",
      features: [
        "Sydney's second CBD",
        "Major commercial and business hub",
        "Modern high-rise apartments",
        "Excellent transport connectivity",
        "Growing employment opportunities",
        "Strong rental yields and capital growth",
      ],
      nearbySuburbs: [
        "North Parramatta",
        "Westmead",
        "Harris Park",
        "Granville",
      ],
      imageQuery: "parramatta cbd sydney second business district",
      route: "/areas/parramatta/suburbs/cbd",
      services: createSuburbServices("Parramatta CBD"),
      pageTexts: createSuburbPageTexts(),
    },
    "parramatta-westmead": {
      id: "parramatta-westmead",
      areaId: "parramatta",
      name: "Westmead",
      slug: "westmead",
      description:
        "Discover Westmead's position as a major health and research precinct. Home to Westmead Hospital and research facilities, this suburb offers excellent growth potential and convenient city access.",
      medianPrice: "$680K",
      growth: "+8.9%",
      population: "11,000",
      features: [
        "Major health and research precinct",
        "Westmead Hospital employment hub",
        "Train station to Sydney CBD",
        "Growing residential developments",
        "Close to Parramatta Park",
        "Strong employment-driven rental demand",
      ],
      nearbySuburbs: [
        "Wentworthville",
        "Girraween",
        "Toongabbie",
        "Merrylands",
      ],
      imageQuery: "westmead parramatta health precinct hospital",
      route: "/areas/parramatta/suburbs/westmead",
      services: createSuburbServices("Westmead"),
      pageTexts: createSuburbPageTexts(),
    },
    "parramatta-harris-park": {
      id: "parramatta-harris-park",
      areaId: "parramatta",
      name: "Harris Park",
      slug: "harris-park",
      description:
        "Experience Harris Park's vibrant multicultural community and excellent value. Known for its diverse dining and close proximity to Parramatta CBD, it offers great opportunities for investors and families.",
      medianPrice: "$650K",
      growth: "+8.5%",
      population: "9,500",
      features: [
        "Vibrant multicultural community",
        "Excellent value properties",
        "Close to Parramatta CBD",
        "Diverse dining and shopping",
        "Good public transport access",
        "Strong rental yields for investors",
      ],
      nearbySuburbs: ["Granville", "Clyde", "Rosehill", "Westmead"],
      imageQuery: "harris park parramatta multicultural affordable",
      route: "/areas/parramatta/suburbs/harris-park",
      services: createSuburbServices("Harris Park"),
      pageTexts: createSuburbPageTexts(),
    },
    "melbourne-cbd": {
      id: "melbourne-cbd",
      areaId: "melbourne",
      name: "Melbourne CBD",
      slug: "cbd",
      description:
        "Experience the heart of Melbourne's business and cultural district. The CBD offers modern apartments, world-class dining, and unmatched convenience with excellent investment potential.",
      medianPrice: "$720K",
      growth: "+2.8%",
      population: "37,000",
      features: [
        "Heart of Melbourne's business district",
        "World-class dining and entertainment",
        "Excellent public transport connections",
        "Cultural attractions and events",
        "High rental yields",
        "Growing residential population",
      ],
      nearbySuburbs: ["Southbank", "Docklands", "Carlton", "East Melbourne"],
      imageQuery: "melbourne cbd skyline",
      route: "/areas/melbourne/suburbs/cbd",
      services: createSuburbServices("Melbourne CBD"),
      pageTexts: createSuburbPageTexts(),
    },
    "melbourne-south-yarra": {
      id: "melbourne-south-yarra",
      areaId: "melbourne",
      name: "South Yarra",
      slug: "south-yarra",
      description:
        "Live in Melbourne's most prestigious and fashionable suburb. South Yarra combines luxury shopping, fine dining, and elegant heritage architecture with excellent tram connections.",
      medianPrice: "$950K",
      growth: "+3.2%",
      population: "22,000",
      features: [
        "Melbourne's most prestigious suburb",
        "Chapel Street shopping and dining",
        "Heritage architecture and character",
        "Excellent tram connections",
        "Royal Botanic Gardens nearby",
        "High-end rental market",
      ],
      nearbySuburbs: ["Toorak", "Prahran", "Richmond", "Windsor"],
      imageQuery: "south yarra melbourne chapel street",
      route: "/areas/melbourne/suburbs/south-yarra",
      services: createSuburbServices("South Yarra"),
      pageTexts: createSuburbPageTexts(),
    },
    "melbourne-brighton": {
      id: "melbourne-brighton",
      areaId: "melbourne",
      name: "Brighton",
      slug: "brighton",
      description:
        "Enjoy Melbourne's premier beachside lifestyle in Brighton. This prestigious suburb offers beautiful beaches, heritage homes, and excellent schools, making it perfect for families and investors.",
      medianPrice: "$1.3M",
      growth: "+2.5%",
      population: "23,000",
      features: [
        "Premier beachside location",
        "Iconic Brighton Beach boxes",
        "Excellent private schools",
        "Heritage homes and character",
        "Bay Street shopping strip",
        "Strong family market",
      ],
      nearbySuburbs: ["Hampton", "Sandringham", "Bentleigh", "Brighton East"],
      imageQuery: "brighton melbourne beach boxes",
      route: "/areas/melbourne/suburbs/brighton",
      services: createSuburbServices("Brighton"),
      pageTexts: createSuburbPageTexts(),
    },
    "melbourne-richmond": {
      id: "melbourne-richmond",
      areaId: "melbourne",
      name: "Richmond",
      slug: "richmond",
      description:
        "Experience Richmond's vibrant inner-city lifestyle. Known for its eclectic mix of old and new, Richmond offers trendy bars, restaurants, and converted warehouses with easy CBD access.",
      medianPrice: "$840K",
      growth: "+4.1%",
      population: "26,000",
      features: [
        "Trendy inner-city lifestyle",
        "Vibrant bar and restaurant scene",
        "Converted warehouse apartments",
        "Bridge Road shopping strip",
        "Close to MCG and sports precinct",
        "Strong rental demand",
      ],
      nearbySuburbs: ["Collingwood", "Fitzroy", "Cremorne", "South Yarra"],
      imageQuery: "richmond melbourne inner city",
      route: "/areas/melbourne/suburbs/richmond",
      services: createSuburbServices("Richmond"),
      pageTexts: createSuburbPageTexts(),
    },
    "melbourne-st-kilda": {
      id: "melbourne-st-kilda",
      areaId: "melbourne",
      name: "St Kilda",
      slug: "st-kilda",
      description:
        "Live Melbourne's bohemian beachside culture in St Kilda. Famous for its pier, foreshore, and vibrant nightlife, St Kilda offers unique character and strong investment opportunities.",
      medianPrice: "$730K",
      growth: "+3.7%",
      population: "19,000",
      features: [
        "Iconic St Kilda Pier and beach",
        "Vibrant arts and music scene",
        "Acland Street cake shops",
        "Luna Park entertainment",
        "Bohemian beachside culture",
        "Strong tourism rental market",
      ],
      nearbySuburbs: ["St Kilda East", "Elwood", "Balaclava", "Windsor"],
      imageQuery: "st kilda melbourne pier",
      route: "/areas/melbourne/suburbs/st-kilda",
      services: createSuburbServices("St Kilda"),
      pageTexts: createSuburbPageTexts(),
    },
    "melbourne-docklands": {
      id: "melbourne-docklands",
      areaId: "melbourne",
      name: "Docklands",
      slug: "docklands",
      description:
        "Experience modern waterfront living in Melbourne's newest urban precinct. Docklands offers contemporary apartments, shopping, and entertainment with spectacular harbor views and city convenience.",
      medianPrice: "$650K",
      growth: "+1.9%",
      population: "15,000",
      features: [
        "Modern waterfront precinct",
        "Contemporary apartment living",
        "Harbor Town shopping outlet",
        "Waterfront dining and entertainment",
        "Close to CBD and transport",
        "Growing residential community",
      ],
      nearbySuburbs: [
        "Melbourne CBD",
        "West Melbourne",
        "Port Melbourne",
        "Southbank",
      ],
      imageQuery: "docklands melbourne waterfront",
      route: "/areas/melbourne/suburbs/docklands",
      services: createSuburbServices("Docklands"),
      pageTexts: createSuburbPageTexts(),
    },
    "melbourne-fitzroy": {
      id: "melbourne-fitzroy",
      areaId: "melbourne",
      name: "Fitzroy",
      slug: "fitzroy",
      description:
        "Experience Melbourne's bohemian heart in trendy Fitzroy. This inner-city suburb offers vibrant street art, eclectic bars, and a thriving cultural scene with excellent investment potential.",
      medianPrice: "$890K",
      growth: "+4.5%",
      population: "10,500",
      features: [
        "Melbourne's bohemian cultural heart",
        "World-renowned street art scene",
        "Trendy bars and live music venues",
        "Brunswick Street shopping and dining",
        "Close to CBD and public transport",
        "Strong rental demand from young professionals",
      ],
      nearbySuburbs: [
        "Collingwood",
        "Carlton North",
        "North Melbourne",
        "Abbotsford",
      ],
      imageQuery: "fitzroy melbourne street art bohemian",
      route: "/areas/melbourne/suburbs/fitzroy",
      services: createSuburbServices("Fitzroy"),
      pageTexts: createSuburbPageTexts(),
    },
    "melbourne-carlton": {
      id: "melbourne-carlton",
      areaId: "melbourne",
      name: "Carlton",
      slug: "carlton",
      description:
        "Discover Carlton's Italian heritage and university atmosphere. Home to the University of Melbourne and authentic Italian dining, Carlton offers character properties and strong rental yields.",
      medianPrice: "$820K",
      growth: "+3.8%",
      population: "18,500",
      features: [
        "Rich Italian heritage and culture",
        "University of Melbourne nearby",
        "Lygon Street dining precinct",
        "Beautiful Victorian architecture",
        "Carlton Gardens and museums",
        "Strong student rental market",
      ],
      nearbySuburbs: ["Carlton North", "Parkville", "Melbourne CBD", "Fitzroy"],
      imageQuery: "carlton melbourne italian university lygon street",
      route: "/areas/melbourne/suburbs/carlton",
      services: createSuburbServices("Carlton"),
      pageTexts: createSuburbPageTexts(),
    },
    "melbourne-prahran": {
      id: "melbourne-prahran",
      areaId: "melbourne",
      name: "Prahran",
      slug: "prahran",
      description:
        "Live in Prahran's vibrant shopping and entertainment hub. Known for Chapel Street's fashion boutiques and nightlife, Prahran offers excellent lifestyle and strong investment opportunities.",
      medianPrice: "$780K",
      growth: "+4.2%",
      population: "12,500",
      features: [
        "Chapel Street fashion and shopping hub",
        "Vibrant nightlife and entertainment",
        "Prahran Market fresh produce",
        "Excellent tram connections",
        "Mix of apartments and heritage homes",
        "Strong rental yields from young professionals",
      ],
      nearbySuburbs: ["South Yarra", "Windsor", "St Kilda East", "Armadale"],
      imageQuery: "prahran melbourne chapel street shopping nightlife",
      route: "/areas/melbourne/suburbs/prahran",
      services: createSuburbServices("Prahran"),
      pageTexts: createSuburbPageTexts(),
    },
    "melbourne-toorak": {
      id: "melbourne-toorak",
      areaId: "melbourne",
      name: "Toorak",
      slug: "toorak",
      description:
        "Experience Melbourne's most exclusive suburb in prestigious Toorak. Known for luxury properties, high-end shopping, and leafy streets, Toorak represents the pinnacle of Melbourne living.",
      medianPrice: "$2.1M",
      growth: "+2.8%",
      population: "12,500",
      features: [
        "Melbourne's most prestigious address",
        "Luxury properties and mansions",
        "Toorak Village high-end shopping",
        "Beautiful tree-lined streets",
        "Excellent private schools nearby",
        "Blue-chip investment location",
      ],
      nearbySuburbs: ["South Yarra", "Armadale", "Malvern", "Kooyong"],
      imageQuery: "toorak melbourne luxury prestigious mansions",
      route: "/areas/melbourne/suburbs/toorak",
      services: createSuburbServices("Toorak"),
      pageTexts: createSuburbPageTexts(),
    },
    "melbourne-hawthorn": {
      id: "melbourne-hawthorn",
      areaId: "melbourne",
      name: "Hawthorn",
      slug: "hawthorn",
      description:
        "Discover Hawthorn's perfect blend of family living and urban convenience. With excellent schools, leafy streets, and good transport links, Hawthorn is ideal for families and professionals.",
      medianPrice: "$1.2M",
      growth: "+3.5%",
      population: "22,000",
      features: [
        "Excellent family suburb",
        "Top-rated public and private schools",
        "Glenferrie Road shopping and dining",
        "Beautiful heritage architecture",
        "Good train and tram connections",
        "Strong family rental market",
      ],
      nearbySuburbs: ["Camberwell", "Richmond", "Kew", "Glen Iris"],
      imageQuery: "hawthorn melbourne family schools leafy streets",
      route: "/areas/melbourne/suburbs/hawthorn",
      services: createSuburbServices("Hawthorn"),
      pageTexts: createSuburbPageTexts(),
    },
    "melbourne-camberwell": {
      id: "melbourne-camberwell",
      areaId: "melbourne",
      name: "Camberwell",
      slug: "camberwell",
      description:
        "Experience Camberwell's family-friendly atmosphere and excellent amenities. Known for great schools, parks, and shopping, Camberwell offers quality living with strong property values.",
      medianPrice: "$1.3M",
      growth: "+3.2%",
      population: "20,500",
      features: [
        "Premium family-friendly suburb",
        "Excellent public and private schools",
        "Burke Road shopping strip",
        "Beautiful parks and gardens",
        "Good public transport access",
        "Consistently strong property values",
      ],
      nearbySuburbs: ["Hawthorn", "Canterbury", "Glen Iris", "Ashburton"],
      imageQuery: "camberwell melbourne family premium schools parks",
      route: "/areas/melbourne/suburbs/camberwell",
      services: createSuburbServices("Camberwell"),
      pageTexts: createSuburbPageTexts(),
    },
    "perth-cbd": {
      id: "perth-cbd",
      areaId: "perth",
      name: "Perth CBD",
      slug: "cbd",
      description:
        "Live in the heart of Western Australia's business capital. Perth CBD offers modern apartments, riverside parks, and vibrant city life with easy access to beaches and business districts.",
      medianPrice: "$550K",
      growth: "+3.5%",
      population: "21,000",
      features: [
        "Heart of WA business district",
        "Swan River and Kings Park nearby",
        "Growing apartment market",
        "Excellent transport connections",
        "Vibrant nightlife and dining",
        "Strong rental yields",
      ],
      nearbySuburbs: ["Northbridge", "West Perth", "East Perth", "South Perth"],
      imageQuery: "perth cbd skyline swan river",
      route: "/areas/perth/suburbs/cbd",
      services: createSuburbServices("Perth CBD"),
      pageTexts: createSuburbPageTexts(),
    },
    "perth-fremantle": {
      id: "perth-fremantle",
      areaId: "perth",
      name: "Fremantle",
      slug: "fremantle",
      description:
        "Discover the historic charm and vibrant culture of Fremantle. This port city offers heritage architecture, bustling markets, and coastal lifestyle with excellent growth prospects.",
      medianPrice: "$720K",
      growth: "+5.1%",
      population: "29,000",
      features: [
        "Historic port city charm",
        "Fremantle Markets and cafe culture",
        "Beautiful heritage architecture",
        "Close to beaches and harbor",
        "Strong tourism and rental market",
        "Arts and cultural hub",
      ],
      nearbySuburbs: [
        "South Fremantle",
        "White Gum Valley",
        "Beaconsfield",
        "Hamilton Hill",
      ],
      imageQuery: "fremantle perth historic",
      route: "/areas/perth/suburbs/fremantle",
      services: createSuburbServices("Fremantle"),
      pageTexts: createSuburbPageTexts(),
    },
    "perth-joondalup": {
      id: "perth-joondalup",
      areaId: "perth",
      name: "Joondalup",
      slug: "joondalup",
      description:
        "Experience the convenience of Perth's northern business hub. Joondalup offers modern amenities, excellent transport, and proximity to beautiful northern beaches with strong growth potential.",
      medianPrice: "$520K",
      growth: "+4.8%",
      population: "33,000",
      features: [
        "Major northern business hub",
        "Modern shopping and facilities",
        "Train line to Perth CBD",
        "Close to northern beaches",
        "ECU Joondalup campus nearby",
        "Growing family community",
      ],
      nearbySuburbs: ["Currambine", "Iluka", "Burns Beach", "Kinross"],
      imageQuery: "joondalup perth business district",
      route: "/areas/perth/suburbs/joondalup",
      services: createSuburbServices("Joondalup"),
      pageTexts: createSuburbPageTexts(),
    },
    "perth-subiaco": {
      id: "perth-subiaco",
      areaId: "perth",
      name: "Subiaco",
      slug: "subiaco",
      description:
        "Live in Perth's trendy inner-western suburb known for its vibrant cafe culture, boutique shopping, and proximity to the city. Subiaco offers character homes and modern apartments with excellent amenities.",
      medianPrice: "$680K",
      growth: "+3.9%",
      population: "19,000",
      features: [
        "Trendy inner-western suburb",
        "Vibrant Rokeby Road dining",
        "Subiaco Oval entertainment",
        "Character homes and modern apartments",
        "Close to Perth CBD",
        "Strong rental market",
      ],
      nearbySuburbs: ["West Perth", "Shenton Park", "Daglish", "Nedlands"],
      imageQuery: "subiaco perth rokeby road",
      route: "/areas/perth/suburbs/subiaco",
      services: createSuburbServices("Subiaco"),
      pageTexts: createSuburbPageTexts(),
    },
    "perth-mandurah": {
      id: "perth-mandurah",
      areaId: "perth",
      name: "Mandurah",
      slug: "mandurah",
      description:
        "Enjoy relaxed coastal living in Western Australia's premier waterfront city. Mandurah offers beautiful waterways, recreational boating, and affordable family lifestyle with growing popularity.",
      medianPrice: "$480K",
      growth: "+6.2%",
      population: "84,000",
      features: [
        "Premier waterfront city",
        "Beautiful waterways and canals",
        "Recreational boating lifestyle",
        "Affordable family living",
        "Growing retirement community",
        "Strong tourism market",
      ],
      nearbySuburbs: ["Halls Head", "Dawesville", "Greenfields", "Falcon"],
      imageQuery: "mandurah perth waterfront canals",
      route: "/areas/perth/suburbs/mandurah",
      services: createSuburbServices("Mandurah"),
      pageTexts: createSuburbPageTexts(),
    },
    "perth-rockingham": {
      id: "perth-rockingham",
      areaId: "perth",
      name: "Rockingham",
      slug: "rockingham",
      description:
        "Discover affordable coastal living south of Perth. Rockingham offers beautiful beaches, growing infrastructure, and excellent value for families and first home buyers in Perth's expanding corridor.",
      medianPrice: "$450K",
      growth: "+7.3%",
      population: "109,000",
      features: [
        "Affordable coastal living",
        "Beautiful beaches and bays",
        "Growing infrastructure investment",
        "Family-friendly community",
        "Excellent value for money",
        "Strong growth corridor",
      ],
      nearbySuburbs: [
        "Safety Bay",
        "Warnbro",
        "Port Kennedy",
        "Secret Harbour",
      ],
      imageQuery: "rockingham perth beach coastal",
      route: "/areas/perth/suburbs/rockingham",
      services: createSuburbServices("Rockingham"),
      pageTexts: createSuburbPageTexts(),
    },
    "perth-scarborough": {
      id: "perth-scarborough",
      areaId: "perth",
      name: "Scarborough",
      slug: "scarborough",
      description:
        "Experience Perth's premier beachside lifestyle in revitalized Scarborough. With its beautiful beach, new developments, and vibrant foreshore, Scarborough offers excellent coastal living and investment potential.",
      medianPrice: "$650K",
      growth: "+5.8%",
      population: "14,500",
      features: [
        "Premier beachside location",
        "Beautiful Scarborough Beach",
        "Revitalized foreshore development",
        "Vibrant cafe and restaurant scene",
        "Close to Perth CBD",
        "Strong tourism and rental market",
      ],
      nearbySuburbs: ["Osborne Park", "Innaloo", "Doubleview", "North Beach"],
      imageQuery: "scarborough perth beach foreshore revitalized",
      route: "/areas/perth/suburbs/scarborough",
      services: createSuburbServices("Scarborough"),
      pageTexts: createSuburbPageTexts(),
    },
    "perth-cottesloe": {
      id: "perth-cottesloe",
      areaId: "perth",
      name: "Cottesloe",
      slug: "cottesloe",
      description:
        "Live in Perth's most prestigious beachside suburb. Cottesloe offers stunning beaches, heritage charm, and exclusive properties, making it the epitome of Perth's coastal luxury living.",
      medianPrice: "$1.2M",
      growth: "+4.2%",
      population: "7,500",
      features: [
        "Perth's most prestigious beach suburb",
        "World-famous Cottesloe Beach",
        "Heritage charm and character",
        "Exclusive beachside properties",
        "Close to Fremantle and Perth",
        "Blue-chip investment location",
      ],
      nearbySuburbs: [
        "Claremont",
        "Peppermint Grove",
        "Mosman Park",
        "Nedlands",
      ],
      imageQuery: "cottesloe perth prestigious beach heritage",
      route: "/areas/perth/suburbs/cottesloe",
      services: createSuburbServices("Cottesloe"),
      pageTexts: createSuburbPageTexts(),
    },
    "perth-midland": {
      id: "perth-midland",
      areaId: "perth",
      name: "Midland",
      slug: "midland",
      description:
        "Discover Midland's combination of heritage charm and modern convenience. This growing suburb offers excellent value, good transport links, and strong investment potential in Perth's eastern corridor.",
      medianPrice: "$480K",
      growth: "+6.8%",
      population: "28,000",
      features: [
        "Heritage charm with modern amenities",
        "Midland Gate shopping center",
        "Train station to Perth CBD",
        "Growing arts and cultural scene",
        "Excellent value for families",
        "Strong rental yields for investors",
      ],
      nearbySuburbs: ["Swan View", "Guildford", "Bassendean", "Caversham"],
      imageQuery: "midland perth heritage value families transport",
      route: "/areas/perth/suburbs/midland",
      services: createSuburbServices("Midland"),
      pageTexts: createSuburbPageTexts(),
    },
    "perth-armadale": {
      id: "perth-armadale",
      areaId: "perth",
      name: "Armadale",
      slug: "armadale",
      description:
        "Experience Armadale's growth potential and affordability. This southeastern suburb offers excellent value for families and investors, with good transport links and growing infrastructure investment.",
      medianPrice: "$420K",
      growth: "+7.9%",
      population: "37,000",
      features: [
        "Excellent affordability for families",
        "Armadale Shopping City center",
        "Train line to Perth CBD",
        "Growing infrastructure investment",
        "Close to Perth Hills",
        "Strong growth potential for investors",
      ],
      nearbySuburbs: ["Kelmscott", "Gosnells", "Seville Grove", "Byford"],
      imageQuery: "armadale perth affordable families growth potential",
      route: "/areas/perth/suburbs/armadale",
      services: createSuburbServices("Armadale"),
      pageTexts: createSuburbPageTexts(),
    },
    "perth-kalamunda": {
      id: "perth-kalamunda",
      areaId: "perth",
      name: "Kalamunda",
      slug: "kalamunda",
      description:
        "Enjoy Perth Hills living in scenic Kalamunda. This elevated suburb offers cooler climate, stunning views, and a strong community atmosphere, perfect for families seeking a tree-change lifestyle.",
      medianPrice: "$580K",
      growth: "+5.5%",
      population: "25,000",
      features: [
        "Beautiful Perth Hills location",
        "Cooler climate and elevated views",
        "Strong community atmosphere",
        "Close to national parks and hiking",
        "Good schools and family amenities",
        "Unique lifestyle investment opportunity",
      ],
      nearbySuburbs: [
        "Lesmurdie",
        "Forrestfield",
        "High Wycombe",
        "Maida Vale",
      ],
      imageQuery: "kalamunda perth hills elevated views community",
      route: "/areas/perth/suburbs/kalamunda",
      services: createSuburbServices("Kalamunda"),
      pageTexts: createSuburbPageTexts(),
    },
    "perth-wanneroo": {
      id: "perth-wanneroo",
      areaId: "perth",
      name: "Wanneroo",
      slug: "wanneroo",
      description:
        "Discover Wanneroo's family-friendly growth potential in Perth's expanding northern corridor. This suburb offers new developments, excellent value, and convenient access to beaches and city.",
      medianPrice: "$540K",
      growth: "+8.1%",
      population: "32,000",
      features: [
        "Fast-growing northern corridor suburb",
        "New residential developments",
        "Family-friendly community",
        "Close to northern beaches",
        "Good value for growing families",
        "Strong rental demand and growth",
      ],
      nearbySuburbs: ["Banksia Grove", "Clarkson", "Butler", "Ridgewood"],
      imageQuery: "wanneroo perth northern corridor families growth",
      route: "/areas/perth/suburbs/wanneroo",
      services: createSuburbServices("Wanneroo"),
      pageTexts: createSuburbPageTexts(),
    },
    "adelaide-cbd": {
      id: "adelaide-cbd",
      areaId: "adelaide",
      name: "Adelaide CBD",
      slug: "cbd",
      description:
        "Experience the heart of South Australia's capital city. Adelaide CBD offers elegant heritage architecture, world-class dining, and convenient city living with excellent value compared to other capitals.",
      medianPrice: "$420K",
      growth: "+2.1%",
      population: "25,000",
      features: [
        "Elegant heritage architecture",
        "World-class dining scene",
        "Free city circle tram",
        "Central Market nearby",
        "Adelaide Festival Centre",
        "Excellent value for capital city",
      ],
      nearbySuburbs: ["North Adelaide", "Parklands", "Kent Town", "Thebarton"],
      imageQuery: "adelaide cbd heritage architecture",
      route: "/areas/adelaide/suburbs/cbd",
      services: createSuburbServices("Adelaide CBD"),
      pageTexts: createSuburbPageTexts(),
    },
    "adelaide-glenelg": {
      id: "adelaide-glenelg",
      areaId: "adelaide",
      name: "Glenelg",
      slug: "glenelg",
      description:
        "Enjoy Adelaide's premier beachside lifestyle in historic Glenelg. Famous for its jetty, beach, and tram connection to the city, Glenelg offers relaxed coastal living with strong rental appeal.",
      medianPrice: "$620K",
      growth: "+3.4%",
      population: "15,500",
      features: [
        "Historic beachside suburb",
        "Famous Glenelg Jetty and beach",
        "Direct tram to Adelaide CBD",
        "Jetty Road shopping strip",
        "Strong tourism and rental market",
        "Relaxed coastal lifestyle",
      ],
      nearbySuburbs: [
        "Glenelg North",
        "Glenelg South",
        "Brighton",
        "Somerton Park",
      ],
      imageQuery: "glenelg adelaide beach jetty",
      route: "/areas/adelaide/suburbs/glenelg",
      services: createSuburbServices("Glenelg"),
      pageTexts: createSuburbPageTexts(),
    },
  },
  allIds: [
    "sydney-cbd",
    "sydney-bondi",
    "sydney-manly",
    "sydney-chatswood",
    "sydney-hornsby",
    "sydney-liverpool",
    "sydney-bankstown",
    "sydney-blacktown",
    "penrith-cbd",
    "penrith-st-marys",
    "penrith-kingswood",
    "parramatta-cbd",
    "parramatta-westmead",
    "parramatta-harris-park",
    "melbourne-cbd",
    "melbourne-south-yarra",
    "melbourne-brighton",
    "melbourne-richmond",
    "melbourne-st-kilda",
    "melbourne-docklands",
    "melbourne-fitzroy",
    "melbourne-carlton",
    "melbourne-prahran",
    "melbourne-toorak",
    "melbourne-hawthorn",
    "melbourne-camberwell",
    "perth-cbd",
    "perth-fremantle",
    "perth-joondalup",
    "perth-subiaco",
    "perth-mandurah",
    "perth-rockingham",
    "perth-scarborough",
    "perth-cottesloe",
    "perth-midland",
    "perth-armadale",
    "perth-kalamunda",
    "perth-wanneroo",
    "adelaide-cbd",
    "adelaide-glenelg",
  ],
};

// Helper functions to work with the normalized data
export const getAreaById = (areaId: string): Area | undefined =>
  areas.byId[areaId];
export const getSuburbById = (suburbId: string): Suburb | undefined =>
  suburbs.byId[suburbId];
export const getSuburbsByAreaId = (areaId: string): Suburb[] => {
  return (
    areas.byId[areaId]?.suburbs?.map((suburbId) => suburbs.byId[suburbId]) || []
  );
};
export const getAllAreas = (): Area[] =>
  areas.allIds.map((id) => areas.byId[id]);
export const getAllSuburbs = (): Suburb[] =>
  suburbs.allIds.map((id) => suburbs.byId[id]);

// Route helpers
export const getAreaRoute = (areaId: string): string | undefined =>
  areas.byId[areaId]?.route;
export const getSuburbRoute = (suburbId: string): string | undefined =>
  suburbs.byId[suburbId]?.route;

// Get major suburbs for an area with name and route info
export const getMajorSuburbsForArea = (
  areaId: string
): Array<{ name: string; route: string }> => {
  const area = areas.byId[areaId];
  if (!area?.suburbs) return [];

  return area.suburbs
    .map((suburbId) => {
      const suburb = suburbs.byId[suburbId];
      return {
        name: suburb?.name || suburbId,
        route: suburb?.route || `/areas/${areaId}/suburbs/${suburbId}`,
      };
    })
    .filter(Boolean);
};

// ===== DERIVED VALUES (NO DUPLICATION) =====
// These functions ensure single source of truth by deriving data from base constants

// Derive navigation from base data
export const getDerivedNavigation = () => ({
  main: [
    { label: "Home", href: "/" },
    {
      label: "Services",
      href: "#",
      dropdown: SERVICES.main.map((service) => ({
        label: service.title,
        href: service.href,
      })),
    },
    {
      label: "Areas",
      href: "#",
      dropdown: areas.allIds.map((areaId) => {
        const area = areas.byId[areaId];
        return { label: area.name, href: `/areas/${areaId}` };
      }),
    },
    { label: "Calculator", href: "/calculator" },
    { label: "Blog", href: "/blog" },
    { label: "Contact", href: "#contact", isScroll: true },
    { label: "About", href: "#about", isScroll: true },
  ],
  footer: {
    sections: [
      {
        title: "Services",
        links: [
          ...SERVICES.main.map((service) => ({
            label: service.title,
            href: service.href,
          })),
          { label: "Loan Calculator", href: "/calculator" },
        ],
      },
      {
        title: "Areas We Serve",
        links: areas.allIds.map((areaId) => {
          const area = areas.byId[areaId];
          return { label: area.name, href: `/areas/${areaId}` };
        }),
      },
      {
        title: "Resources",
        links: [
          { label: "Finance Blog", href: "/blog" },
          {
            label: "First Home Buyer Guide",
            href: "/blog/first-home-buyer-guide",
          },
          {
            label: "Investment Property Tips",
            href: "/blog/investment-property-tips",
          },
          { label: "Refinancing Guide", href: "/blog/refinancing-guide" },
          { label: "Market Updates", href: "/blog/market-updates" },
        ],
      },
    ],
  },
});

// Derive hero content for areas
export const getDerivedAreaHero = (areaName: string) => ({
  heroTitle: `${areaName} Mortgage Brokers`,
  heroSubtitle: SERVICES.main[0].title, // Dynamically use first service (Home Loans)
  heroDescription: `Get expert mortgage advice and competitive home loan rates in ${areaName}. Our experienced brokers help you secure the best deal for your property investment.`,
});

// Derive area statistics
export const getDerivedAreaStats = (areaName: string) => ({
  experience: "15+",
  experienceLabel: "Years Experience",
  loans: `In ${areaName} Home Loans`,
  suburbs: "25+",
  suburbsLabel: `${areaName} Suburbs Covered`,
});

// Derive area services
export const getDerivedAreaServices = (areaName: string) => [
  {
    title: `${areaName} Home Loans`,
    description: `First home buyers, refinancing, and investment loans in ${areaName}`,
    icon: "Home",
  },
  {
    title: `${areaName} Refinancing`,
    description: `Switch to better rates and save on your ${areaName} property`,
    icon: "Star",
  },
];

// Derive area display names and descriptions
export const getDerivedAreaInfo = (areaName: string) => ({
  displayName: `${areaName} ${COMPANY_INFO.tagline} Experts`,
  description: `Expert mortgage brokers serving ${areaName} and surrounding suburbs. We understand the unique property market and help you secure competitive home loan rates across ${areaName}'s diverse neighborhoods.`,
});

// Derive suburb-specific content
export const getDerivedSuburbInfo = (suburbName: string, areaName: string) => ({
  heroTitle: `${suburbName} Mortgage Brokers`,
  heroDescription: `Get expert mortgage advice and competitive home loan rates in ${suburbName}, ${areaName}. Our experienced brokers help you secure the best deal for your property investment.`,
  aboutTitle: `About ${suburbName}`,
  aboutDescription: `${suburbName} is a vibrant suburb in ${areaName}, offering excellent property investment opportunities and lifestyle benefits for residents.`,
});
